# Generated by Django 6.0.2 on 2026-03-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_username_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="paid_method",
            new_name="payment_method",
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
